baseurl = "https://nilesh7756.github.io/myblog/"
languageCode = "en-us"
title = "Nilesh's BLOG "
publishDir = "docs"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "nileshkube"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
themesDir = "themes"

[params]
    site_author = "Nilesh Suryavanshi"
    site_description = "The awesome blog of Nilesh Suryavanshi"
    location = "India"
    # Link custom assets relative to /static
    avatar = "img/profile-image.png"
    header_background = "img/desk.jpg"
    header_title = "Nilesh Suryavanshi"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "nilesh7756"
    facebook  = ""
    linkedin  = "nilesh-suryavanshi-69ba5262"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "nilesh7756"
    gplus     = ""
